_target_: torch.compile
mode: default
fullgraph: true
model:
  _target_: rmind.components.timm_backbone.TimmBackbone
  model_name: vit_small_patch16_dinov3.lvd1689m
  # model_name: vit_base_patch16_dinov3.lvd1689m
  # model_name: vit_huge_plus_patch16_dinov3.lvd1689m
  # model_name: vit_large_patch16_dinov3.lvd1689m
  # model_name: vit_base_patch16_siglip_256
  freeze: True
  out_indices: [10]
  img_size: [256, 256]


