_target_: torch.compile
mode: default
fullgraph: true
model:
  _target_: rmind.components.timm_backbone.TimmBackbone
  # model_name: vit_large_patch16_siglip_512
  # model_name: vit_so400m_patch16_siglip_512
  model_name: vit_base_patch16_siglip_512
  freeze: True
  out_indices: [10]
  img_size: [512, 512]


