# _target_: rmind.models.control_transformer.ControlTransformer
# _recursive_: false
# _convert_: all

# episode_builder:
#   _target_: rmind.components.episode.EpisodeBuilder
#   _recursive_: true
#   _convert_: all
#   timestep:
#     - [observation, image, cam_front_left]


#   input_transform:
#     _target_: torch.nn.Sequential
#     _convert_: all
#     _args_:
#       - _target_: rmind.components.nn.Remapper
#         paths:
#           image:
#             cam_front_left: [data, cam_front_left]

#       - _target_: rmind.components.containers.ModuleDict
#         modules:
#           image:
#             _target_: torch.nn.Sequential
#             _args_:
#               - _target_: einops.layers.torch.Rearrange
#                 pattern: "... h w c -> ... c h w"
#               - _target_: torchvision.transforms.v2.CenterCrop
#                 size: [320, 576]
#               - _target_: torchvision.transforms.v2.Resize
#                 size: [256, 256]
#               - _target_: torchvision.transforms.v2.ToDtype
#                 scale: true
#                 dtype:
#                   _target_: hydra.utils.get_object
#                   path: torch.float32
#               - _target_: torchvision.transforms.v2.Normalize
#                 mean: [0.485, 0.456, 0.406]
#                 std: [0.229, 0.224, 0.225]



#   tokenizers:
#     _target_: rmind.components.containers.ModuleDict
#     modules:
#       image:
#         _target_: rmind.components.nn.Identity


#   embeddings:
# _target_: rmind.components.containers.ModuleDict
# modules:
#   image:
    # _target_: torch.nn.Sequential
    # _args_:
      # - _target_: rmind.components.timm_backbone.TimmBackbone
      #   model_name: vit_small_patch16_dinov3.lvd1689m
      #   freeze: True
      #   out_indices: [10]
      #   img_size: [256, 256]
      # - _target_: einops.layers.torch.Rearrange
      #   pattern: "... c h w -> ... (h w) c"
_target_: rmind.components.timm_backbone.TimmBackbone
# model_name: vit_small_patch16_dinov3.lvd1689m
# model_name: vit_huge_plus_patch16_dinov3.lvd1689m
# model_name: vit_large_patch16_dinov3.lvd1689m
# SigLip models
# model_name: vit_large_patch16_siglip_512
# model_name: vit_so400m_patch16_siglip_512
model_name: vit_base_patch16_siglip_512
freeze: True
out_indices: [10]
img_size: [512, 512]


